--------------------------------------------------------
--BORRAR TABLA
DROP TABLE CUERPOS_CELESTES;
--BORRAR OBJETO
DROP TYPE CUERPO_CELESTE;
--CREAR TIPO OBJETO
  CREATE OR REPLACE NONEDITIONABLE TYPE CUERPO_CELESTE AS OBJECT(
   codigo NUMBER, nombre VARCHAR(20), tipo VARCHAR(20), diametro NUMBER
);

/
--------------------------------------------------------
-- CREAR TABLA
  CREATE TABLE CUERPOS_CELESTES OF CUERPO_CELESTE 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HCUERPOS_CELESTES
SET DEFINE OFF;
-- BORRAR CLAVE PRIMARIA
-- ALTER TABLE CUERPOS_CELESTES DROP CONSTRAINT pk_cuerpos_celestes;
-- ASIGNAR CLAVE PRIMARIA
-- ALTER TABLE CUERPOS_CELESTES ADD CONSTRAINT pk_cuerpos_celestes PRIMARY KEY (codigo);

--------------------------------------------------------
--  Constraints for Table CUERPOS_CELESTES
--------------------------------------------------------

 -- ALTER TABLE CUERPOS_CELESTES ADD UNIQUE ("SYS_NC_OID$") RELY
 -- USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 -- STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 -- PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 -- BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 -- TABLESPACE "USERS"  ENABLE;
 commit;
