

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora2
     */
    private double resultado;
    boolean limpiarTexto;
    boolean sePuedeCalcular;
    boolean primerOperando;
    char ultimoOperando;
    String operandoActual;

    public Calculadora() {
        initComponents();
        this.resultado = 0.0;
        this.operandoActual = "0.0";
        this.limpiarTexto = true;
        this.sePuedeCalcular = false;
        this.primerOperando = true;
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teclaPresionada(evt);
            }
        });
        setFocusable(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void teclaPresionada(java.awt.event.KeyEvent evt) {
        char tecla = evt.getKeyChar();

        if (Character.isDigit(tecla) || tecla == '.') {
            // Si es un d�gito, actualizar el texto en la pantalla
            if (this.limpiarTexto) {
                this.txtResultado.setText(Character.toString(tecla));
                this.limpiarTexto = false;
            } else {
                this.txtResultado.setText(this.txtResultado.getText() + tecla);
            }
            this.sePuedeCalcular = true;
        } else {
            // Si es un operador, realizar la operaci�n correspondiente
            switch (tecla) {
                case '+':
                    btnPlusActionPerformed(null);
                    break;
                case '-':
                    btnMinusActionPerformed(null);
                    break;
                case '*':
                    btnMultActionPerformed(null);
                    break;
                case '/':
                    btnDivActionPerformed(null);
                    break;
                case '\n':
                    btnEqualActionPerformed(null);
                    break;
                case '\b':
                    // Si es la tecla de retroceso, borrar un car�cter
                    String textoActual = this.txtResultado.getText();
                    if (!textoActual.isEmpty()) {
                        this.txtResultado.setText(textoActual.substring(0, textoActual.length() - 1));
                    }
                    break;
                case 'c':
                case 'C':
                    // Si es 'C' (may�scula o min�scula), limpiar la pantalla
                    btnClearActionPerformed(null);
                    break;
                case '\u007F':
                    btnClearAllActionPerformed(null);
                    break;
                default:
                    break;
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(51, 51, 51));
        setIconImage(new ImageIcon("calculadora.png").getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel2.setLayout(new java.awt.BorderLayout(5, 0));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.setText("0");
        txtResultado.setToolTipText("Caja de resultado");
        txtResultado.setName(""); // NOI18N
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        txtResultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultadoKeyTyped(evt);
            }
        });
        jPanel2.add(txtResultado, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(213, 213, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 350));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnPlus.setBackground(new java.awt.Color(51, 51, 51));
        btnPlus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(0, 204, 0));
        btnPlus.setText("+");
        btnPlus.setToolTipText("boton plus");
        btnPlus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlus.setPreferredSize(new java.awt.Dimension(70, 40));
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus);

        btnMinus.setBackground(new java.awt.Color(51, 51, 51));
        btnMinus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(0, 204, 0));
        btnMinus.setText("-");
        btnMinus.setToolTipText("boton minus");
        btnMinus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMinus.setPreferredSize(new java.awt.Dimension(70, 40));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinus);

        btnMult.setBackground(new java.awt.Color(51, 51, 51));
        btnMult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMult.setForeground(new java.awt.Color(0, 204, 0));
        btnMult.setText("x");
        btnMult.setToolTipText("boton mult");
        btnMult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMult.setPreferredSize(new java.awt.Dimension(70, 40));
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });
        jPanel1.add(btnMult);

        btnDiv.setBackground(new java.awt.Color(51, 51, 51));
        btnDiv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(0, 204, 0));
        btnDiv.setText("/");
        btnDiv.setToolTipText("boton div");
        btnDiv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDiv.setPreferredSize(new java.awt.Dimension(70, 40));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        jPanel1.add(btnDiv);

        btn7.setBackground(new java.awt.Color(51, 51, 51));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setToolTipText("boton 7");
        btn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.setPreferredSize(new java.awt.Dimension(70, 40));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setBackground(new java.awt.Color(51, 51, 51));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setToolTipText("boton 8");
        btn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.setPreferredSize(new java.awt.Dimension(70, 40));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setToolTipText("boton 9");
        btn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.setPreferredSize(new java.awt.Dimension(70, 40));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        btnClear.setBackground(new java.awt.Color(51, 51, 51));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 0, 0));
        btnClear.setText("C");
        btnClear.setToolTipText("boton clear");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.setPreferredSize(new java.awt.Dimension(70, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);

        btn4.setBackground(new java.awt.Color(51, 51, 51));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setToolTipText("boton 4");
        btn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.setPreferredSize(new java.awt.Dimension(70, 40));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setBackground(new java.awt.Color(51, 51, 51));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setToolTipText("boton 5");
        btn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.setPreferredSize(new java.awt.Dimension(70, 40));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setBackground(new java.awt.Color(51, 51, 51));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setToolTipText("boton 6");
        btn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.setPreferredSize(new java.awt.Dimension(70, 40));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btnClearAll.setBackground(new java.awt.Color(51, 51, 51));
        btnClearAll.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClearAll.setForeground(new java.awt.Color(255, 0, 0));
        btnClearAll.setText("CE");
        btnClearAll.setToolTipText("boton clear all");
        btnClearAll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClearAll.setPreferredSize(new java.awt.Dimension(70, 40));
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearAll);

        btn1.setBackground(new java.awt.Color(51, 51, 51));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setToolTipText("boton 1");
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.setPreferredSize(new java.awt.Dimension(70, 40));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setBackground(new java.awt.Color(51, 51, 51));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setToolTipText("boton 2");
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.setPreferredSize(new java.awt.Dimension(70, 40));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setBackground(new java.awt.Color(51, 51, 51));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setToolTipText("boton 3");
        btn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.setPreferredSize(new java.awt.Dimension(70, 40));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btndot.setBackground(new java.awt.Color(51, 51, 51));
        btndot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndot.setForeground(new java.awt.Color(255, 255, 255));
        btndot.setText(".");
        btndot.setToolTipText("boton 0");
        btndot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndot.setPreferredSize(new java.awt.Dimension(70, 40));
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });
        jPanel1.add(btndot);

        btn0.setBackground(new java.awt.Color(51, 51, 51));
        btn0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setToolTipText("boton 0");
        btn0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn0.setPreferredSize(new java.awt.Dimension(70, 40));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);

        btnEqual.setBackground(new java.awt.Color(0, 153, 0));
        btnEqual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(255, 255, 255));
        btnEqual.setText("=");
        btnEqual.setToolTipText("boton equal");
        btnEqual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEqual.setPreferredSize(new java.awt.Dimension(230, 40));
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel1.add(btnEqual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "0";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "0";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "1";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "1";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
     }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "2";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "2";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "3";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "3";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "4";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "4";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "5";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "5";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;


    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "6";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "6";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "7";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "7";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "8";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "8";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (this.limpiarTexto) {
            this.operandoActual = "9";
            this.limpiarTexto = false;
        } else {
            this.operandoActual += "9";
        }
        this.txtResultado.setText(this.operandoActual);
        this.sePuedeCalcular = true;
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        btnEqualActionPerformed(evt);
        this.txtResultado.setText("0");
        this.ultimoOperando = '+';
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        btnEqualActionPerformed(evt);
        this.txtResultado.setText("0");
        this.ultimoOperando = '-';
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        btnEqualActionPerformed(evt);
        this.txtResultado.setText("0");
        this.ultimoOperando = '*';
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        btnEqualActionPerformed(evt);
        this.txtResultado.setText("0");
        this.ultimoOperando = '/';
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        if (this.sePuedeCalcular) {
            double operandoActual = Double.parseDouble(this.operandoActual);
            if (this.primerOperando) {
                resultado = operandoActual;
                this.primerOperando = false;
            } else {
                switch (this.ultimoOperando) {
                    case '+':
                        resultado += operandoActual;
                        break;
                    case '-':
                        resultado -= operandoActual;
                        break;
                    case '*':
                        resultado *= operandoActual;
                        break;
                    case '/':
                        if (operandoActual == 0) {
                            JOptionPane.showMessageDialog(this, "No se puede dividir entre 0");
                        } else {
                            resultado /= operandoActual;
                        }
                        break;
                }
            }
            this.operandoActual = String.valueOf(this.resultado);
                    this.txtResultado.setText(String.format("%.2f", this.resultado));
            this.txtResultado.setText(this.resultado + "");
            this.limpiarTexto = true;
            this.sePuedeCalcular = false;
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.txtResultado.setText("0");
        this.primerOperando = false;
        this.limpiarTexto = true;
        this.sePuedeCalcular = false;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        this.txtResultado.setText("0");
        this.resultado = 0;
        this.primerOperando = true;
        this.limpiarTexto = true;
        this.sePuedeCalcular = false;
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void txtResultadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultadoKeyTyped
    }//GEN-LAST:event_txtResultadoKeyTyped

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed

    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        if (!this.operandoActual.contains(".")) {
            this.operandoActual += ".";
            this.txtResultado.setText(this.operandoActual);
        }
    }//GEN-LAST:event_btndotActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btndot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
