package ejercicio2.entornografico;

import static ejercicio2.funcionalidad.Funcionalidad.*;
import javax.swing.JOptionPane;

public class EntornoGrafico extends javax.swing.JFrame {

    public EntornoGrafico() {
        initComponents();
        recuperarFichero();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAnadir = new javax.swing.JDialog();
        labelTituloAnadir = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        labelDiametro = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        txtDiametro = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmbElegirTipo = new javax.swing.JComboBox<>();
        labelPistaCodigo = new javax.swing.JLabel();
        labelPistaDiametro = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jDialogMostrar = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuerposCelestes = new javax.swing.JTable();
        jDialogBuscarPorCodigo = new javax.swing.JDialog();
        btnBuscar = new javax.swing.JButton();
        labelTituloBuscarCodigo = new javax.swing.JLabel();
        labelCodigoBuscar = new javax.swing.JLabel();
        txtBuscarPorCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuscarPorCodigo = new javax.swing.JTable();
        jDialogBuscarPorTipo = new javax.swing.JDialog();
        btnTipoBuscar = new javax.swing.JButton();
        labelTituloBuscarTipo = new javax.swing.JLabel();
        labelTipoBuscar = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableBuscarPorTipo = new javax.swing.JTable();
        cmbTipoBuscar = new javax.swing.JComboBox<>();
        jDialogBorrarCuerpo = new javax.swing.JDialog();
        btnEliminarCuerpo = new javax.swing.JButton();
        labelBorrarCuerposCelestes = new javax.swing.JLabel();
        labelCodigoBorrar = new javax.swing.JLabel();
        txtBorrarPorCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAnadir = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnBuscarCodigo = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        btnBuscarTipo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBorrarCuerpo = new javax.swing.JButton();

        jDialogAnadir.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogAnadir.setTitle("Añadir Cuerpos Celestes");
        jDialogAnadir.setBackground(new java.awt.Color(51, 51, 51));
        jDialogAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelTituloAnadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTituloAnadir.setForeground(new java.awt.Color(0, 153, 0));
        labelTituloAnadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloAnadir.setText("Añadir Cuerpos Celestes");
        labelTituloAnadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre.setText("Nombre");

        labelCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigo.setText("Codigo");

        labelDiametro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDiametro.setText("Diámetro");

        labelTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipo.setText("Tipo");

        txtDiametro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiametro.setActionCommand("<Not Set>");
        txtDiametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiametroActionPerformed(evt);
            }
        });
        txtDiametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiametroKeyTyped(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        cmbElegirTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbElegirTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planeta", "Luna", "Planeta Enano" }));
        cmbElegirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbElegirTipoActionPerformed(evt);
            }
        });

        labelPistaCodigo.setForeground(new java.awt.Color(153, 152, 152));
        labelPistaCodigo.setText("El código de ser de 3 dígitos.");

        labelPistaDiametro.setForeground(new java.awt.Color(153, 152, 152));
        labelPistaDiametro.setText("Máximo 6 dígitos.");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAnadirLayout = new javax.swing.GroupLayout(jDialogAnadir.getContentPane());
        jDialogAnadir.getContentPane().setLayout(jDialogAnadirLayout);
        jDialogAnadirLayout.setHorizontalGroup(
            jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAnadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jDialogAnadirLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCodigo)
                    .addComponent(labelNombre)
                    .addComponent(labelTipo)
                    .addComponent(labelDiametro))
                .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAnadirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbElegirTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(jDialogAnadirLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPistaCodigo)
                            .addComponent(txtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogAnadirLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(labelPistaDiametro))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDialogAnadirLayout.setVerticalGroup(
            jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAnadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloAnadir)
                .addGap(18, 18, 18)
                .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPistaCodigo)
                .addGap(18, 18, 18)
                .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbElegirTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo))
                .addGap(18, 18, 18)
                .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiametro)
                    .addComponent(txtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPistaDiametro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jDialogAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addGap(18, 18, 18))
        );

        jDialogMostrar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogMostrar.setTitle("Mostrar Cuerpos Celestes");

        jTableCuerposCelestes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Tipo", "Diámetro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCuerposCelestes);

        javax.swing.GroupLayout jDialogMostrarLayout = new javax.swing.GroupLayout(jDialogMostrar.getContentPane());
        jDialogMostrar.getContentPane().setLayout(jDialogMostrarLayout);
        jDialogMostrarLayout.setHorizontalGroup(
            jDialogMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMostrarLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogMostrarLayout.setVerticalGroup(
            jDialogMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jDialogBuscarPorCodigo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogBuscarPorCodigo.setTitle("Buscar por código");

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelTituloBuscarCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTituloBuscarCodigo.setForeground(new java.awt.Color(0, 0, 204));
        labelTituloBuscarCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloBuscarCodigo.setText("Buscar Cuerpos Celestes por código");
        labelTituloBuscarCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelCodigoBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigoBuscar.setText("Código");

        txtBuscarPorCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscarPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPorCodigoActionPerformed(evt);
            }
        });
        txtBuscarPorCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarPorCodigoKeyTyped(evt);
            }
        });

        jTableBuscarPorCodigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Tipo", "Diámetro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBuscarPorCodigo.setToolTipText("");
        jScrollPane2.setViewportView(jTableBuscarPorCodigo);

        javax.swing.GroupLayout jDialogBuscarPorCodigoLayout = new javax.swing.GroupLayout(jDialogBuscarPorCodigo.getContentPane());
        jDialogBuscarPorCodigo.getContentPane().setLayout(jDialogBuscarPorCodigoLayout);
        jDialogBuscarPorCodigoLayout.setHorizontalGroup(
            jDialogBuscarPorCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBuscarPorCodigoLayout.createSequentialGroup()
                .addGroup(jDialogBuscarPorCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogBuscarPorCodigoLayout.createSequentialGroup()
                        .addGroup(jDialogBuscarPorCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogBuscarPorCodigoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCodigoBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(jDialogBuscarPorCodigoLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(labelTituloBuscarCodigo)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jDialogBuscarPorCodigoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogBuscarPorCodigoLayout.setVerticalGroup(
            jDialogBuscarPorCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBuscarPorCodigoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelTituloBuscarCodigo)
                .addGap(18, 18, 18)
                .addGroup(jDialogBuscarPorCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(labelCodigoBuscar)
                    .addComponent(txtBuscarPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogBuscarPorTipo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogBuscarPorTipo.setTitle("Buscar por Tipo");
        jDialogBuscarPorTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnTipoBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTipoBuscar.setText("Buscar");
        btnTipoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoBuscarActionPerformed(evt);
            }
        });

        labelTituloBuscarTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTituloBuscarTipo.setForeground(new java.awt.Color(0, 0, 204));
        labelTituloBuscarTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloBuscarTipo.setText("Buscar Cuerpos Celestes por tipo");
        labelTituloBuscarTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelTipoBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipoBuscar.setText("Tipo");

        jTableBuscarPorTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Tipo", "Diámetro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBuscarPorTipo.setToolTipText("");
        jScrollPane4.setViewportView(jTableBuscarPorTipo);

        cmbTipoBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planeta", "Luna", "Planeta enano" }));

        javax.swing.GroupLayout jDialogBuscarPorTipoLayout = new javax.swing.GroupLayout(jDialogBuscarPorTipo.getContentPane());
        jDialogBuscarPorTipo.getContentPane().setLayout(jDialogBuscarPorTipoLayout);
        jDialogBuscarPorTipoLayout.setHorizontalGroup(
            jDialogBuscarPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBuscarPorTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogBuscarPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jDialogBuscarPorTipoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelTipoBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTipoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTipoBuscar)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialogBuscarPorTipoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(labelTituloBuscarTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogBuscarPorTipoLayout.setVerticalGroup(
            jDialogBuscarPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBuscarPorTipoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelTituloBuscarTipo)
                .addGap(18, 18, 18)
                .addGroup(jDialogBuscarPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipoBuscar)
                    .addComponent(labelTipoBuscar)
                    .addComponent(cmbTipoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogBorrarCuerpo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDialogBorrarCuerpoKeyTyped(evt);
            }
        });

        btnEliminarCuerpo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarCuerpo.setText("Borrar");
        btnEliminarCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuerpoActionPerformed(evt);
            }
        });

        labelBorrarCuerposCelestes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelBorrarCuerposCelestes.setForeground(new java.awt.Color(153, 0, 51));
        labelBorrarCuerposCelestes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBorrarCuerposCelestes.setText("Borrar Cuerpos Celestes");
        labelBorrarCuerposCelestes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelCodigoBorrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigoBorrar.setText("Código");

        txtBorrarPorCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBorrarPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrarPorCodigoActionPerformed(evt);
            }
        });
        txtBorrarPorCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBorrarPorCodigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jDialogBorrarCuerpoLayout = new javax.swing.GroupLayout(jDialogBorrarCuerpo.getContentPane());
        jDialogBorrarCuerpo.getContentPane().setLayout(jDialogBorrarCuerpoLayout);
        jDialogBorrarCuerpoLayout.setHorizontalGroup(
            jDialogBorrarCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBorrarCuerpoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelCodigoBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogBorrarCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogBorrarCuerpoLayout.createSequentialGroup()
                        .addComponent(txtBorrarPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCuerpo))
                    .addGroup(jDialogBorrarCuerpoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelBorrarCuerposCelestes)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jDialogBorrarCuerpoLayout.setVerticalGroup(
            jDialogBorrarCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBorrarCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBorrarCuerposCelestes)
                .addGap(18, 18, 18)
                .addGroup(jDialogBorrarCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBorrarPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCuerpo)
                    .addComponent(labelCodigoBorrar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRADOR DE CUERPOS CELESTESS");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnAnadir.setBackground(new java.awt.Color(0, 168, 0));
        btnAnadir.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir.setText("Añadir Cuerpos Celestes");
        btnAnadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnadir.setMaximumSize(new java.awt.Dimension(500, 45));
        btnAnadir.setMinimumSize(new java.awt.Dimension(500, 45));
        btnAnadir.setPreferredSize(new java.awt.Dimension(500, 50));
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnMostrar.setBackground(new java.awt.Color(79, 79, 172));
        btnMostrar.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Mostrar Cuerpos Celestes");
        btnMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrar.setMaximumSize(new java.awt.Dimension(500, 45));
        btnMostrar.setMinimumSize(new java.awt.Dimension(500, 45));
        btnMostrar.setPreferredSize(new java.awt.Dimension(500, 50));
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnBuscarCodigo.setBackground(new java.awt.Color(235, 141, 0));
        btnBuscarCodigo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnBuscarCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCodigo.setText("Buscar Cuerpos Celestes por código");
        btnBuscarCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCodigo.setMaximumSize(new java.awt.Dimension(500, 45));
        btnBuscarCodigo.setMinimumSize(new java.awt.Dimension(500, 45));
        btnBuscarCodigo.setPreferredSize(new java.awt.Dimension(500, 50));
        btnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoActionPerformed(evt);
            }
        });

        btnBorrarTodo.setBackground(new java.awt.Color(102, 0, 0));
        btnBorrarTodo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnBorrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarTodo.setText("Borrar todo");
        btnBorrarTodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarTodo.setPreferredSize(new java.awt.Dimension(247, 50));
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });

        btnBuscarTipo.setBackground(new java.awt.Color(235, 141, 0));
        btnBuscarTipo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnBuscarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTipo.setText("Buscar Cuerpos Celestes por tipo");
        btnBuscarTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarTipo.setMaximumSize(new java.awt.Dimension(500, 45));
        btnBuscarTipo.setMinimumSize(new java.awt.Dimension(500, 45));
        btnBuscarTipo.setPreferredSize(new java.awt.Dimension(500, 50));
        btnBuscarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTipoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(238, 238, 144));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPreferredSize(new java.awt.Dimension(247, 50));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnBorrarCuerpo.setBackground(new java.awt.Color(102, 0, 0));
        btnBorrarCuerpo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnBorrarCuerpo.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarCuerpo.setText("Borrar Cuerpos Celestes");
        btnBorrarCuerpo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarCuerpo.setMaximumSize(new java.awt.Dimension(500, 45));
        btnBorrarCuerpo.setMinimumSize(new java.awt.Dimension(500, 45));
        btnBorrarCuerpo.setPreferredSize(new java.awt.Dimension(500, 50));
        btnBorrarCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuerpoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAnadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarCuerpo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int res = JOptionPane.showConfirmDialog(
                rootPane,
                "¿Quieres salir del programa?",
                "Salir",
                JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        jDialogAnadir.setVisible(true);
        jDialogAnadir.setSize(450, 375);
        jDialogAnadir.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if (listarCuerposCelestes() == 0) {
            JOptionPane.showMessageDialog(rootPane, "No hay datos en el fichero.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            listarCuerposCelestes();
            jDialogMostrar.setVisible(true);
            jDialogMostrar.setSize(473, 400);
            jDialogMostrar.setLocationRelativeTo(null);

        }

    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        jDialogBuscarPorCodigo.setVisible(true);
        jDialogBuscarPorCodigo.setSize(450, 400);
        jDialogBuscarPorCodigo.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    private void btnBuscarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTipoActionPerformed
        jDialogBuscarPorTipo.setVisible(true);
        jDialogBuscarPorTipo.setSize(450, 400);
        jDialogBuscarPorTipo.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnBuscarTipoActionPerformed

    private void btnBorrarCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuerpoActionPerformed
        jDialogBorrarCuerpo.setVisible(true);
        jDialogBorrarCuerpo.setSize(380, 150);
        jDialogBorrarCuerpo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBorrarCuerpoActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        int res = JOptionPane.showConfirmDialog(
                rootPane,
                "¿Desea realmente borrar el archivo de datos?",
                "Borrado de datos",
                JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            borrarTodo();
        }
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void cmbElegirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbElegirTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbElegirTipoActionPerformed

    private void btnTipoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoBuscarActionPerformed
        buscarCuerpoPorTipo();

    }//GEN-LAST:event_btnTipoBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jDialogAnadir.dispose();
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDiametro.setText("");
        cmbElegirTipo.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (anadirCuerpoCeleste()) {
            JOptionPane.showMessageDialog(rootPane, "Cuerpo Celeste añadido con éxito.", "Cuerpo añadido", JOptionPane.INFORMATION_MESSAGE);
            txtCodigo.setText("");
            txtCodigo.requestFocus();
            txtNombre.setText("");
            txtDiametro.setText("");
            cmbElegirTipo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarCuerpoPorCodigo();
        txtBuscarPorCodigo.requestFocus();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed

    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDiametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiametroActionPerformed

    }//GEN-LAST:event_txtDiametroActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (txtNombre.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        if (txtCodigo.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtDiametroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametroKeyTyped
        if (txtDiametro.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDiametroKeyTyped

    private void txtBuscarPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPorCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPorCodigoActionPerformed

    private void txtBuscarPorCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorCodigoKeyTyped
        if (txtBuscarPorCodigo.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarPorCodigoKeyTyped

    private void btnEliminarCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuerpoActionPerformed

        borrarCuerpoCeleste();
        txtBorrarPorCodigo.setText("");

    }//GEN-LAST:event_btnEliminarCuerpoActionPerformed

    private void txtBorrarPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrarPorCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBorrarPorCodigoActionPerformed

    private void txtBorrarPorCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBorrarPorCodigoKeyTyped
        if (txtBorrarPorCodigo.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBorrarPorCodigoKeyTyped

    private void jDialogBorrarCuerpoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDialogBorrarCuerpoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogBorrarCuerpoKeyTyped
    public static void errorMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                getFileData();
////                if (Funcionalidad.cuerposCelestes.isEmpty()) {
////                    createFile();
////                }
//                new EntornoGrafico().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBorrarCuerpo;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCodigo;
    private javax.swing.JButton btnBuscarTipo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarCuerpo;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTipoBuscar;
    public static javax.swing.JComboBox<String> cmbElegirTipo;
    public static javax.swing.JComboBox<String> cmbTipoBuscar;
    private javax.swing.JDialog jDialogAnadir;
    private javax.swing.JDialog jDialogBorrarCuerpo;
    private javax.swing.JDialog jDialogBuscarPorCodigo;
    private javax.swing.JDialog jDialogBuscarPorTipo;
    private javax.swing.JDialog jDialogMostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTableBuscarPorCodigo;
    public static javax.swing.JTable jTableBuscarPorTipo;
    public static javax.swing.JTable jTableCuerposCelestes;
    private javax.swing.JLabel labelBorrarCuerposCelestes;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelCodigoBorrar;
    private javax.swing.JLabel labelCodigoBuscar;
    private javax.swing.JLabel labelDiametro;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPistaCodigo;
    private javax.swing.JLabel labelPistaDiametro;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTipoBuscar;
    private javax.swing.JLabel labelTituloAnadir;
    private javax.swing.JLabel labelTituloBuscarCodigo;
    private javax.swing.JLabel labelTituloBuscarTipo;
    public static javax.swing.JTextField txtBorrarPorCodigo;
    public static javax.swing.JTextField txtBuscarPorCodigo;
    public static javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtDiametro;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
